import type { RfqItem, RfqContact, RfqDelivery } from '@/core/types/rfq-schemas'
import { formatCurrency } from '@/core/utils/helpers'

export interface PdfRfqData {
  reference: string
  date: string
  status: string
  items: RfqItem[]
  contact: RfqContact
  delivery?: RfqDelivery | null
  notes?: string
  urgency: string
  budgetRange?: string
  estimatedTotal: number
  categories: string[]
}

export function generatePdfSummary(data: PdfRfqData): string {
  const lines: string[] = []

  lines.push('ALL BUSINESS NEEDS')
  lines.push('Procurement Request for Quotation')
  lines.push('='.repeat(50))
  lines.push('')

  lines.push(`Reference: ${data.reference}`)
  lines.push(`Date: ${data.date}`)
  lines.push(`Status: ${data.status}`)
  lines.push(`Urgency: ${data.urgency}`)
  lines.push('')

  lines.push('CONTACT INFORMATION')
  lines.push('-'.repeat(50))
  lines.push(`Name: ${data.contact.full_name}`)
  lines.push(`Title: ${data.contact.job_title || 'N/A'}`)
  lines.push(`Company: ${data.contact.company}`)
  lines.push(`Department: ${data.contact.department || 'N/A'}`)
  lines.push(`Email: ${data.contact.email}`)
  lines.push(`Phone: ${data.contact.phone}`)
  lines.push('')

  if (data.delivery) {
    lines.push('DELIVERY ADDRESS')
    lines.push('-'.repeat(50))
    lines.push(data.delivery.address_line1)
    if (data.delivery.address_line2) lines.push(data.delivery.address_line2)
    lines.push(`${data.delivery.city}, ${data.delivery.state || ''} ${data.delivery.postal_code}`)
    if (data.delivery.delivery_instructions) {
      lines.push('')
      lines.push(`Instructions: ${data.delivery.delivery_instructions}`)
    }
    lines.push('')
  }

  lines.push(`PROCUREMENT ITEMS (${data.items.length})`)
  lines.push('-'.repeat(50))
  lines.push('')

  data.items.forEach((item, index) => {
    lines.push(`${index + 1}. ${item.product_name}`)
    lines.push(`   SKU: ${item.sku || 'N/A'}`)
    if (item.brand) lines.push(`   Brand: ${item.brand}`)
    lines.push(`   Quantity: ${item.quantity}`)
    if (item.unit_price || item.target_price) {
      lines.push(`   Unit Price: ${formatCurrency(item.unit_price || item.target_price || 0)}`)
      lines.push(`   Line Total: ${formatCurrency((item.unit_price || item.target_price || 0) * item.quantity)}`)
    }
    if (item.specifications) lines.push(`   Specifications: ${item.specifications}`)
    if (item.notes) lines.push(`   Notes: ${item.notes}`)
    lines.push('')
  })

  lines.push('='.repeat(50))
  lines.push(`Estimated Total: ${formatCurrency(data.estimatedTotal)}`)

  if (data.budgetRange) {
    lines.push(`Budget Range: ${data.budgetRange}`)
  }

  if (data.notes) {
    lines.push('')
    lines.push('PROCUREMENT NOTES')
    lines.push('-'.repeat(50))
    lines.push(data.notes)
  }

  lines.push('')
  lines.push('='.repeat(50))
  lines.push('Generated by All Business Needs Procurement Platform')
  lines.push('This document is a quotation request, not a purchase order.')

  return lines.join('\n')
}

export function downloadRfqPdf(data: PdfRfqData, filename?: string) {
  const content = generatePdfSummary(data)
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename || `${data.reference}-RFQ.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function generateEmailPayload(data: PdfRfqData): { subject: string; body: string } {
  const subject = `RFQ: ${data.reference} - ${data.contact.company} (${data.items.length} items)`

  const body = `Dear Sales Team,

Please find below our Request for Quotation.

Reference: ${data.reference}
Company: ${data.contact.company}
Contact: ${data.contact.full_name}
Email: ${data.contact.email}
Phone: ${data.contact.phone}

Items (${data.items.length}):
${data.items.map((item, i) => `${i + 1}. ${item.product_name} (SKU: ${item.sku || 'N/A'}) - Qty: ${item.quantity}`).join('\n')}

${data.notes ? `Additional Notes:\n${data.notes}\n` : ''}
Urgency: ${data.urgency}
${data.budgetRange ? `Budget Range: ${data.budgetRange}` : ''}

Please provide your quotation at your earliest convenience.

Best regards,
${data.contact.full_name}
${data.contact.job_title || ''}
${data.contact.company}`

  return { subject, body }
}
